#!/usr/bin/env bash
to_spinal_case() {
    echo "$1" | \
    iconv -f utf-8 -t ascii//TRANSLIT | \
    tr '[:upper:]' '[:lower:]' | \
    sed 's/[^a-z0-9 _-]//g' | \
    sed 's/[ _]/-/g' | \
    sed 's/-\+/-/g' | \
    sed 's/^-//;s/-$//'
}

# Avoid poisoning template remote
git remote rm origin
yarn && yarn prepare

echo Some questions about the script :
read -rp "Title: " title
read -rp "Description: " desc
read -rp "Version: " version
read -rp "Target url (@match): " match
slug="$(to_spinal_case "$title")"

# Create README
printf "# %s\n\n%s" "$title" "$desc" > README.md
cat instructions.md >> README.md

# Create script
printf "// ==UserScript==
// @name     %s
// @version  %s
// @match    %s
// @grant    none
// ==/UserScript==
" "$title" "$version" "$match" > "${slug}.user.js"

# Rename sublime-project file
mv sublime-project.sublime-project "${slug}.sublime-project"

# Auto-delete
unlink instructions.md
unlink "$0"
